### ISSUE TITLE
Fix the phone number input fieds 

### ISSUE THREAD

**Issue by tdadadavid** [Cybtracy/webapp-frontend#17]
The phone number field in the Partnership form
![image](https://github.com/Cybtracy/webapp-frontend/assets/58336536/c8b59fb7-cf04-408a-b5b4-5b9f4f949c2c)

The phone number field in the Volunteer form
![image](https://github.com/Cybtracy/webapp-frontend/assets/58336536/57936285-fc7f-4f80-bb10-f80e27a21768)

This field should be a drop-down of country codes where users can fill in their phone number.

**Comment by darksuei** [comment]
Done
